spring.application.name=u5w3d5
# Import dell' env.properties
spring.config.import=file:env.properties
# Server Config
server.port=${PORT}
# PostgreSQL Config
spring.datasource.url=${PG_URL}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
# JWT secret
jwt.secret=${JWT_SECRET}
